### ISSUE TITLE
动态链接库(DLL)初始化例程失败 Can not import avx core while this file exists paddle\fluid\core_avx.pyd

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/Paddle-Inference-Demo#212]
paddlepaddle_gpu-2.2.1.post112-cp38-cp38-win_amd64.whl
I7 CPU 支持 avx
python 3.8

```python
import argparse
import numpy as np

# 引用 paddle inference 预测库
import paddle.inference as paddle_infer

def main():
    args = parse_args()

    # 创建 config
    config = paddle_infer.Config(args.model_file, args.params_file)

    # 根据 config 创建 predictor
    predictor = paddle_infer.create_predictor(config)

    # 获取输入的名称
    input_names = predictor.get_input_names()
    input_handle = predictor.get_input_handle(input_names[0])

    # 设置输入
    fake_input = np.random.randn(args.batch_size, 3, 318, 318).astype("float32")
    input_handle.reshape([args.batch_size, 3, 318, 318])
    input_handle.copy_from_cpu(fake_input)

    # 运行predictor
    predictor.run()

    # 获取输出
    output_names = predictor.get_output_names()
    output_handle = predictor.get_output_handle(output_names[0])
    output_data = output_handle.copy_to_cpu() # numpy.ndarray类型
    print("Output data size is {}".format(output_data.size))
    print("Output data shape is {}".format(output_data.shape))

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_file", type=str, help="model filename")
    parser.add_argument("--params_file", type=str, help="parameter filename")
    parser.add_argument("--batch_size", type=int, default=1, help="batch size")
    return parser.parse_args()

if __name__ == "__main__":
    main()
```

```
python demo2.py --model_file F:/paddle2/paddle_model/model.pdmodel --params_file 
F:/paddle2/paddle_model/model.pdiparams --batch_size 2

WARNING: Logging before InitGoogleLogging() is written to STDERR
W0105 17:48:08.006067 62532 tensorrt.cc:56] You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
The TensorRT that Paddle depends on is not configured correctly.
  Suggestions:
  1. Check if the TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;%PATH%`
  - Mac: set  DYLD_LIBRARY_PATH by `export DYLD_LIBRARY_PATH=...`
E0105 17:48:08.007102 62532 port.h:50] Load symbol getPluginRegistry failed.

Error: Can not import avx core while this file exists: E:\anaconda3\envs\paddleinference\lib\site-packages\paddle\fluid\core_avx.pyd

Traceback (most recent call last):
  File "demo2.py", line 5, in <module>
    import paddle.inference as paddle_infer
  File "E:\anaconda3\envs\paddleinference\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "E:\anaconda3\envs\paddleinference\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "E:\anaconda3\envs\paddleinference\lib\site-packages\paddle\fluid\framework.py", line 37, in <module>
    from . import core
  File "E:\anaconda3\envs\paddleinference\lib\site-packages\paddle\fluid\core.py", line 294, in <module>
    raise e
  File "E:\anaconda3\envs\paddleinference\lib\site-packages\paddle\fluid\core.py", line 256, in <module>
    from .core_avx import *
ImportError: DLL load failed while importing core_avx: 动态链接库(DLL)初始化例程失败。
```

**Comment by simple123456T** [comment]
你是怎么解决的？
