### ISSUE TITLE
KeyError: "Couldn't find field paddle.framework.proto.OpDesc.output"

### ISSUE THREAD

**Issue by eucommiaulmoides** [PaddlePaddle/Paddle-Inference-Demo#29]
之前python的demo还可以跑，为什么出现了这个错误？
网上查了一下，似乎没有查到解决办法，希望得到大佬的帮助

**Comment by NHZlX** [comment]
有没有更详细的信息。比如单侧+模型？

**Comment by eucommiaulmoides** [comment]
我是在windows环境下运行的python版本yolov3 demo
报错信息如下：
Traceback (most recent call last):
  File "E:/project/paddle/core/Paddle-Inference-Demo/python/yolov3/inference.py", line 5, in <module>
    from paddle.fluid.core import create_paddle_predictor
  File "E:\project\paddle\lib\site-packages\paddle\__init__.py", line 37, in <module>
    import paddle.complex
  File "E:\project\paddle\lib\site-packages\paddle\complex\__init__.py", line 15, in <module>
    from . import tensor
  File "E:\project\paddle\lib\site-packages\paddle\complex\tensor\__init__.py", line 15, in <module>
    from . import math
  File "E:\project\paddle\lib\site-packages\paddle\complex\tensor\math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "E:\project\paddle\lib\site-packages\paddle\common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "E:\project\paddle\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "E:\project\paddle\lib\site-packages\paddle\fluid\framework.py", line 33, in <module>
    from .proto import framework_pb2
  File "E:\project\paddle\lib\site-packages\paddle\fluid\proto\framework_pb2.py", line 453, in <module>
    options=None),
  File "E:\project\paddle\lib\site-packages\google\protobuf\descriptor.py", line 534, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field paddle.framework.proto.OpDesc.output"

我刚开始怀疑事protobuf这个包的问题，换了好几个版本都没用
现在把环境换成了linux可以跑了
捂脸
但很奇怪，之前windows环境是一直可以跑的，我没有改动过

**Comment by NHZlX** [comment]
收到了，这边会验证下
